services:
#    control_movil.example:
#        class: ControlMovilBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    control_movil.admin.control:
        class: UTN\Bundle\ControlMovilBundle\Admin\ControlAdmin
        arguments: [~, UTN\Bundle\ControlMovilBundle\Entity\Control, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Control Móvil }

    control_movil.admin.control_inventario:
        class: UTN\Bundle\ControlMovilBundle\Admin\ControlInventarioAdmin
        arguments: [~, UTN\Bundle\ControlMovilBundle\Entity\ControlInventario, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Control Inventario }
