services:
#    rfid.example:
#        class: RfidBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    rfid.admin.log_movimiento:
        class: UTN\Bundle\RfidBundle\Admin\LogMovimientoAdmin
        arguments: [~, UTN\Bundle\RfidBundle\Entity\LogMovimiento, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Registro de Seguridad }

    rfid.admin.track:
        class: UTN\Bundle\RfidBundle\Admin\Track
        arguments: [~, UTN\Bundle\RfidBundle\Entity\LogMovimiento, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Track de Inventarios }